name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - uses: timkinsman/eslint-action@master
        with:
          autofixes: true
      - run: git add -A
      - run: git commit -m "ESLint"
      - run: git push
